services:
  spectre-dev-server:
    container_name: spectre-dev-server
    image: spectre-dev-server
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    environment:
      - DISPLAY=${DISPLAY} # Enables GUI applications to run.
      - SPECTRE_GID=${SPECTRE_GID}
      - SPECTRE_BIND_HOST=${SPECTRE_BIND_HOST}
      - SPECTRE_BIND_PORT=${SPECTRE_BIND_PORT}
    networks:
      - spectre-dev-network
    volumes:
      - spectre-dev-data:/app/.spectre-data
      - /tmp/.X11-unix:/tmp/.X11-unix # Enables GUI applications to run.
    devices:
      - "/dev/bus/usb"
    ports:
      - ${SPECTRE_PORT_MAP}
    mem_limit: 8g
    shm_size: 8g
    tty: true
    stop_signal: SIGKILL

  spectre-dev-cli:
    container_name: spectre-dev-cli
    image: spectre-dev-cli
    build:
      context: ./cli
      dockerfile: Dockerfile
      target: development
    environment:
      - SPECTRE_SERVER_HOST=${SPECTRE_SERVER_HOST}
      - SPECTRE_SERVER_PORT=${SPECTRE_SERVER_PORT}
    networks:
      - spectre-dev-network
    depends_on:
      - spectre-dev-server
    tty: true
    stop_signal: SIGKILL

networks:
  spectre-dev-network:
    name: spectre-dev-network
    driver: bridge

volumes:
  spectre-dev-data:
    name: spectre-dev-data
