networks:
  spectre-network:
    name: spectre-network
    driver: bridge

services:
  spectre-server:
    build:
      context: backend
      dockerfile: Dockerfile
      target: runtime
    environment:
      - SPECTRE_GID=${SPECTRE_GID}
      - SPECTRE_BIND_HOST=${SPECTRE_BIND_HOST}
      - SPECTRE_BIND_PORT=${SPECTRE_BIND_PORT}
    container_name: spectre-server
    group_add:
      - "${SPECTRE_GID}"
    image: spectre-server
    mem_limit: 8g 
    shm_size: 8g
    networks:
      - spectre-network
    volumes:
      - spectre-data:/app/.spectre-data
    devices:
      - "/dev/bus/usb"
    stop_signal: SIGKILL
    ports:
      - ${SPECTRE_PORT_MAP}
  spectre-cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
      target: runtime
    environment:
      - SPECTRE_SERVER_HOST=${SPECTRE_SERVER_HOST}
      - SPECTRE_SERVER_PORT=${SPECTRE_SERVER_PORT}
    container_name: spectre-cli
    image: spectre-cli
    networks:
      - spectre-network
    depends_on:
      - spectre-server
    # Keep the container running on start-up
    tty: true 
    stop_signal: SIGKILL

volumes:
  spectre-data:
