version: "3.8"

services:
  spectre-server:
    container_name: spectre-server
    image: spectre-server
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    environment:
      - SPECTRE_GID=${SPECTRE_GID}
      - SPECTRE_BIND_HOST=${SPECTRE_BIND_HOST}
      - SPECTRE_BIND_PORT=${SPECTRE_BIND_PORT}
    group_add:
      - "${SPECTRE_GID}"
    networks:
      - spectre-network
    volumes:
      - spectre-data:/app/.spectre-data
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/bus/usb"
    ports:
      - ${SPECTRE_PORT_MAP}
    mem_limit: 8g
    shm_size: 8g
    tty: true
    stop_signal: SIGKILL

  spectre-cli:
    container_name: spectre-cli
    image: spectre-cli
    build:
      context: ./cli
      dockerfile: Dockerfile
      target: development
    environment:
      - SPECTRE_SERVER_HOST=${SPECTRE_SERVER_HOST}
      - SPECTRE_SERVER_PORT=${SPECTRE_SERVER_PORT}
    networks:
      - spectre-network
    depends_on:
      - spectre-server
    tty: true
    stop_signal: SIGKILL

networks:
  spectre-network:
    name: spectre-network
    driver: bridge

volumes:
  spectre-data:
