networks:
  spectre-network:
    driver: bridge

services:
  spectre-server:
    build:
      context: backend
      dockerfile: Dockerfile
      target: uhd
    environment:
      - SPECTRE_SERVICE_HOST=0.0.0.0
      - SPECTRE_SERVICE_PORT=5000
    container_name: spectre-server
    image: spectre-server
    shm_size: 4gb
    networks:
      - spectre-network
    volumes:
      - spectre-data:/app/.spectre-data
    devices:
      - "/dev/bus/usb"
    stop_signal: SIGKILL
    ports:
      - 127.0.0.1:5000:5000
  spectre-cli:
    build:
      context: ./cli
      dockerfile: Dockerfile
      target: runtime
    environment:
      - SPECTRE_SERVICE_HOST=spectre-server
      - SPECTRE_SERVICE_PORT=5000
    container_name: spectre-cli
    image: spectre-cli
    networks:
      - spectre-network
    depends_on:
      - spectre-server
    # Keep the container running on start-up
    tty: true 
    stop_signal: SIGKILL

volumes:
  spectre-data:
