services:
  spectre-dev-server:
    container_name: spectre-dev-server
    image: spectre-dev-server
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    environment:
      - SPECTRE_BIND_HOST=0.0.0.0
      - SPECTRE_BIND_PORT=5001
    networks:
      - spectre-dev-network
    volumes:
      - spectre-dev-data:/app/.spectre-data
    devices:
      - "/dev/bus/usb"
    ports:
      - 127.0.0.1:5001:5001
    mem_limit: 8g
    shm_size: 8g
    tty: true
    stop_signal: SIGKILL

  spectre-dev-cli:
    container_name: spectre-dev-cli
    image: spectre-dev-cli
    build:
      context: ./cli
      dockerfile: Dockerfile
      target: development
    environment:
      - SPECTRE_SERVER_HOST=spectre-dev-server
      - SPECTRE_SERVER_PORT=5001
    networks:
      - spectre-dev-network
    depends_on:
      - spectre-dev-server
    tty: true
    stop_signal: SIGKILL

networks:
  spectre-dev-network:
    name: spectre-dev-network
    driver: bridge

volumes:
  spectre-dev-data:
    name: spectre-dev-data
